apiVersion: apps/v1
kind: Deployment
metadata:
    name: api
spec:
    selector:
      matchLabels:
          app: api
    template:
      metadata:
        labels:
          app: api
      spec:
        containers:
          - name: api
            image: lagcrs/api-bootcamp-produto:v1
            ports:
              - containerPort: 8082
            env:
              - name: MONGODB_URI 
                value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin
              - name: MONGO_INITDB_ROOT_PASSWORD
                value: mongopwd

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - port:  82
      targetPort: 8082
      nodePort: 30000
  type: NodePort